language: node_js
node_js:
- '12'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: qoMmW0M5rKwz1Q5hLM35k3l729FCdQInaq18sz7XuScLwjAalQc4rtWzS0T3DqBeUp4IeNe+iXbsZeaSpwO/TlgfWnNvFxZbUbCGZPDRV1K1ISDpF8ym9VM3peJK8xy2KQUuwMWKhsyi7qeP6P1jTwj2ogwN02EJS3+WJ/RqH0HNoQ8x5aq1K2261r4kSKLuZUG8g2Gfe/73UaPooJSrAOtjWhWkPTT4NOCFrt+I7y/2JPRGsnlj5c862G9E5bTwyydDtr90S2/kpGj6JgzC+/aQFE7arm1m5Vqn1TlfcK7x8xAfAd1nB8SGYPDDpnzGibziQPcjGYEMJOFn+Y1uUPKGxmqEm0FZLOKKh8WaAfiv4apDcfhkDtkViMh627yL5gzLGDk2mnro3lohhWOft1ZRowvI2DdjNWyRt/elV/URmQpj8GEuSE7UpZPBLdagnEBrnF3h6qngnJTq0XiiWJQl2nQ//V9OMXQsXEwjRmwQ0+eA3ZLzH3tC1xvhl9XaSN/IaQ4qR/lrURqE32o0TsHDfHMD7UV/s4N2zSiu6hsh7egAIvieRTx+qbBJkfioPee5ay7JcP2lT8Dporucf5N+fww6lDf06ceSFHykqmZelylLLRUzQU3catLWZHdCx7SoHFl9YVs6kt4s2WgJMZqPGbW2Pq4AMph00D0dVio=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: higlass/higlass-register
  - provider: npm
    email: service@lekschas.de
    api_key:
      secure: c8/0yPdtgRD3rUcpJNT0ngJGRLZlwtToCyp5cUN90noIW9IaCFyRZcpnuZGRGl88WS51O+Uf30I1iyNobIfQmQr7N4SkiijVH+s/UJORFS/nXEAnIYRzwyG++3bOulFuK7U63K6tRKHfrwjFwc9bvhQNuOAHd8Ec5t8e0v59/DccsPE3Hbkce5T4DfcS08LIzKLYxu9xebEJ+v3xZcF3f6RCDr8NBrpxVMO0hBSjI//g3WLj6JZlCe57vCupHEhyIcUvmKzuXe93LhxjTyEAs12uPiu14lrhifI7ZklwlqMrdAd6ZjLtBAlq1SGFjxhgGPOzTT4gzzNkRjS//xarIlRvwVI2fty8LAEoASK5kGZ1S9xrdhXfQO+UurIBR9C+PEtELFLSjqcexYZNM4PyyuBy943XQUKh7s6fjfOGIcyQa+QNuMI8sFIONsHSVNjlHTWutfcKTY0hXNbPyZsHwRJxokZwo3OMJ6xVMTEnJWa/nVoVBZjYrY0ftYwFCgEU2NZNGC6tSmxGKo+mk5cDTb3RupWGom7sG7zXWTLBzYVnnQCjVmIJIyBebLE5CJc7XvwlSzHRVOO48J+q0TBNEX4u70QxVZwi+D7NznjqCEranLW7jbHpT3iRhpG+2F7w39ASBO22qzxE90ZpYfdLSM3dSOKhoPl8UQ96oM24KdA=
    on:
      branch: master
      tags: true
      repo: higlass/higlass-register
