language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: qoMmW0M5rKwz1Q5hLM35k3l729FCdQInaq18sz7XuScLwjAalQc4rtWzS0T3DqBeUp4IeNe+iXbsZeaSpwO/TlgfWnNvFxZbUbCGZPDRV1K1ISDpF8ym9VM3peJK8xy2KQUuwMWKhsyi7qeP6P1jTwj2ogwN02EJS3+WJ/RqH0HNoQ8x5aq1K2261r4kSKLuZUG8g2Gfe/73UaPooJSrAOtjWhWkPTT4NOCFrt+I7y/2JPRGsnlj5c862G9E5bTwyydDtr90S2/kpGj6JgzC+/aQFE7arm1m5Vqn1TlfcK7x8xAfAd1nB8SGYPDDpnzGibziQPcjGYEMJOFn+Y1uUPKGxmqEm0FZLOKKh8WaAfiv4apDcfhkDtkViMh627yL5gzLGDk2mnro3lohhWOft1ZRowvI2DdjNWyRt/elV/URmQpj8GEuSE7UpZPBLdagnEBrnF3h6qngnJTq0XiiWJQl2nQ//V9OMXQsXEwjRmwQ0+eA3ZLzH3tC1xvhl9XaSN/IaQ4qR/lrURqE32o0TsHDfHMD7UV/s4N2zSiu6hsh7egAIvieRTx+qbBJkfioPee5ay7JcP2lT8Dporucf5N+fww6lDf06ceSFHykqmZelylLLRUzQU3catLWZHdCx7SoHFl9YVs6kt4s2WgJMZqPGbW2Pq4AMph00D0dVio=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: hms-dbmi/higlass-register
  - provider: npm
    email: service@lekschas.de
    api_key:
      secure: XwVB/R1fOEiQJ+/GQ5/FpqGnJz2a8/t0nnV8ZRCAr+Rw3sWYF1Vtvv8aF2caL9sFuE9v4+3h8S1m/lu340siiyZu9pfURYdBNZsbF/n3mAu+lDcILSTB2t5GJTFgrWMb3sjAF934nfYv9nYIcGu3FiVVZwB2z/GvYNkvOcdtIZ4gM4N1xuTcNAMaH2WLmN83SMW2zEzQC4mXmM+zXnUWP8yHr/kAm1/murnYZVqz/8QYzsm2HAG+9JtfPkfA3rLXG8U4sY/Mdec/QsNLl1DQw5TSh4Ri38xrY47Q6s/IQAm0WGGEspbSksBuQfDdCOylJdjmzJZBgKOpsKYZqOPZLNRHtDxci4nJdlPVl0Ic7A/0+zJ49WacUgQwzkV8CNhfMu69hP4KQ1QI0scRmkxw02ds/mOy91/iSVdGyi74cU1ExKThVKkFiqgGxzDR3FSxOqxjPAIZb7jKMnPXDnxPdnWD92AblJLQvLGxRfUzZ3oi8RjkdK+4Zz82VbCdYhby49n3Qll6imrLXEMA4dHTz5vG2+ZIOZb+pS1fHs4Qv8ecxjWjsZkyFwEhcqw+GJAvcjfvNCbwc0RfQyvT/0DFhcoCo3liEuil5wFfNvDhkGqCvqD4pkx42Q8NHZap3mMpk5jKOdI0EFQWuOhINs3MNTtr6g4aGulOxafN+Gk/SAE=
    on:
      branch: master
      tags: true
      repo: hms-dbmi/higlass-register
