language: node_js
node_js:
- '12'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: OnT5vc2eM157jtSZUzW3WBKQDp82CiV7aP1TCy+8m4pLuK4dIDumTFgNm9EnQoRcrGTFo75VvDKFZfx89ZZIGT2PqlE9ETeoUh9Mxrm3HJSgZ0/2BijWQJtCBcLAT+TbmWCEsovmOMWuP6Oa+XpRpuwYQyA45sUgsrWVHlh1M0lKKv4DsXGCqCEAN0dT2ZLV+Z+X1QZcXQeGHlDSW6c7KhsGILvQDdBq/BZaSLgWVp0G3t21qalv5GP52wQiGdURZaNPfZD/3trLZSD7ERIMAjqE52mRBlPu2zRfQ2WCgnPTmLq7An8FOcW5lMil93+Vpw4o0bnJF9CpE8ZfYB59j1x6chgbPGQT+Bcl9bF3jh5GemdKMRo0ucVr+ydRbmKESdE99kadLrrL5nKwlM6XnPcRSDq/XcML3UjNyG7ASTNg0WQs8MB2l1/PZPscKPwt90gHxzDr0ljuN6XsFA2sBySNzq3LIYKx4JvUphV3XIllI2ZU47Cjw1zCrUkPCThdVwBoXJvrqrjHYlRCGk0LFuYtpT/phuNtEz7Qp8wFl/74vNPKTfMfOIlmggRphgAkOV8hQqASX1zrrvvL7VgAuQ416rZ71ArorcwF1S2B95ITtuu0IHUiRxsxEYhB4dVbVPkrIOszPt68QX3Hfk0OvvXvCckwhDl5PQClrCAC0kU=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: higlass/higlass-register
  - provider: npm
    email: code@lekschas.de
    api_key:
      secure: nJ3Y6H4ppy2YYADNxwXOq6CeYw5SL5T/HBIGx8sJr4Bi6EWHZxEhBZuogLjRmIMX6FhRVU/oZAh44DEhsdYSsoFEnMOFRVqz+17RTOvx/lBoAlnwhTUiTHbAx/MYLF2BHUUiWn9gMcZ8vv4m+K8EEjdDSPzpZPs0buAPfx8dlxTmN48IUVo9vpfyYz68/6UBlYkIqc65/VknuzNBleLU7ouZXlNEDhpnSRQ/CHuUg+33T+kjKnLPi/zZRTMYOj1cBY0ivkKhkA00co6mkAc2OlgRrjxJQB0SALzAeUoQ0rvzfc+aE+1tAu/A9KaPConZZOYxR4VgIIPjkykg+avVyKRPZdWw0QWZL1/h6iKnUpwkyC5liZpoJd+1iD1fDvc7WGZytMmpWAhBofBWvEnb1LZclkAzpwpPyKezXwUAQMNXI9jI55uH+/Rzn6XUR7pTmrDi6EIzUEYXmMAr2BQul3k/E6yHsQnlO7I/IPz8t/K3ovSqUhodANmLzqqEriMdxHU8pRkplGTdXLhA4ihZWit5Z8zny8jGj1SVXhikdsSyHQrdb8Q+dOcpfVcbpbmwHP57y65usGa0sRf7zORqyXyafKXI4Gd0WpV9rX0bWr7ungI3wVVDIOzeqAx1AwWCj8D+2dB7UlSOv7UYv98ggfLamyoUcgHk3lQNJNgIpjs=
    on:
      branch: master
      tags: true
      repo: higlass/higlass-register
