language: node_js
node_js:
- '12'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ufpXOyC5eo2p1a4n64Vw2kIom4/u/WB6gX74TQGTIt+KKscFURGpJeZibzyPJVPHa/KsWdQRDknp7wdGzWdLQZs/WCCt8TrGP+N4gDjsMi6foR+4jjLddLzYMfeSYBjTmm6rugeK/N6k/xpK4vlFnMXEEy9VaS7udG/NeGiKiGGY5JCqCb9ySsXiTC8Pn5aZuusfV0XosIceYJyYVNzUQv9FH3/FBiJvvQU10Jds30yUr2vqSmND5p8NWSc0DfxDxiFfP06cPYgLQhvXsdcEsKhgSZCAJwsAAcxzg5OF0cuFzRljTk5hpSah6Oc2ORAer0tfhoJJgMKnLVv8+bL1FmwRfL6zuvoMOyEPCJHqPYD2P7owNaCVfkVi3kztnx+Xwk3CfI+TF34u0jFiv46+A3MCOKOLJqOzzO3UTzYa8nbVynxI3yuZE256C8xj5Qbx1ESBZkRnJFc2xP3gcw38GAImoLpZfkAGA3Bk2OxLOlHB8hyJS4P52KooR+FAofwECJN8IklG6Kb69cZnsKhiakkn3OG1q7bbobnsS44tQoq+3iP2w3ZNVP6MGeBUbOgMzC0G8hE6RjQ46xM5xmtAGkAPGxizrd4di9oxG+hT8vvPVZMO3Ynf5UIGnE/sNgQjO4NvFcOPgAkiHk2Hc844U1B0wGEnn2cNo6TNOBAWDbQ=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: higlass/higlass-register
  - provider: npm
    email: code@lekschas.de
    api_key:
      secure: BOt2uRPUN0zM0xIEBoFZ/+rMCrok22ohaoZDzagV29XHMBRdxQ6mz4A/T54fnzt2fgR7l+EIyMkcpKtFOU4S6rKqDOX4zpny1IBBNMwnfkeXG3NDHtT5Lxq5l8GyVarycFJKnhGTi5XDpwhbYYboxRZISsZ4rYiALKYBM/CPEYjHbeLOh4sfj0XeYuj/nI0lj7IUr6gwiZD4fEl6W0caySjy5brnAV29fTLvKo2eRuZctcAOr0sTB1mQh4Ah6NdJR9GdWTc2+F6sZBbb7Qd8vuA9fjZLsYSCJ/Md+/1M9arDlQXj9LBmCwBktBZ6/zrXnWaFvQxpqL6BdMv8L7Hi68C/OX28CpvY2czgU9h8Gc+I6d0NScGsWI4A4RkW1aWLLl3EOfITTm7TpW/dAgA3SXv5rjTTwnJOqOon6/dSphu18obxSRJoTNsb1lWatoc1EXr3jpa1UsdwUWZJLBet3F1cW6HmEr+5C0/ei8yz47MCoeZs/VV5WkVOML6SRHj9MlgQt6RXlUduN/apPFT6LipXoHfomCRCBGltKBEbTkXWnfrIeGj/2g+ToSoKa6MYucPoCmF3TGTr025ikdZX8qUQuYXhNxR9CCUH+dCNACiC6cL2WSaIeMIYeOkKPdX/DV0/kx3guD6Td1Tq2b+BMbHO/9yUE6M703n4OHJUiZM=
    on:
      branch: master
      tags: true
      repo: higlass/higlass-register
